[package]
name = "token_faucet"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.7"

[dependencies.spl-token]
version = "4.0.1"
default-features = false
features = ["no-entrypoint"]

[lib]
name = "token_faucet"
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"